[http]
  # Add the router
  [http.routers]
    [http.routers.http-to-https]
      entryPoints = ["web"]
      middlewares = ["redirect-to-https"]
      rule = "HostRegexp(`{host:.+}`)"
      service = "noop@internal"

  [http.middlewares]
    [http.middlewares.redirect-to-https.redirectScheme]
      scheme = "https"
    [http.middlewares.admin-auth.basicAuth]
      users = ["smartateam:${admin_basic_auth_enrcypted_password}"]
